version: '3'
services:
  postgres:
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
volumes:
  database-data: # named volumes can be managed easier using docker-compose