version: '2.2'
services:
  postgis:
    image: cheewai/postgis
    env_file:
      - .env
    environment:
      - DEBUG=false
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always